### ISSUE TITLE
Cannot connect TTN Server

### ISSUE THREAD

**Issue by oziesin** [lorabasics/basicstation#153] opened 2022-02-16 11:48 UTC
Hi , i am trying to connect my gateway to TTN. I created necessery files like below maybe it was be incomplete.
![folder](https://user-images.githubusercontent.com/54961819/154257729-28b28ba9-322e-43aa-a470-5828560d3bff.png)

i created .key files and .trust file by ttn guide.

my station.conf file is this way
station.conf
{
    /* If slave-X.conf present this acts as default settings */
    "SX1301_conf": {		     /* Actual channel plan is controlled by server */
	"lorawan_public": true,      /* is default */
        "clksrc": 1,		     /* radio_1 provides clock to concentrator */
	/* path to the SPI device, un-comment if not specified on the command line e.g., RADIODEV=/dev/spidev0.0 */
	"device": "/dev/spidev0.1",  
	/* freq/enable provided by LNS - only HW specific settings listed here */
	"radio_0": {
	    "type": "SX1257",
	    "rssi_offset": -166.0,
	    "tx_enable": true,
	    "antenna_gain": 0
	}
    },
    "station_conf": {
	"log_file":  "stderr", /* "station.log" */
	"log_level": "DEBUG",  /* XDEBUG,DEBUG,VERBOSE,INFO,NOTICE,WARNING,ERROR,CRITICAL */
	"log_size":  10000000,
	"log_rotate":  3,
	"CUPS_RESYNC_INTV": "1s",
	 /*"device": "/dev/spidev0.1",*/
        "radio_init": "rinit.sh",
        "RADIO_INIT_WAIT": "2s",
        "RX_POLL_INTV": "10ms",
        "TC_TIMEOUT": "360s"
    }
}
tc.uri file contains wss://eu1.cloud.thethings.network:443

I coppied all files to my device and i run .station and i faced screen below
![basic](https://user-images.githubusercontent.com/54961819/154258173-bdc9fa70-fe47-4346-8821-1f7c5a4faac8.png)

How could i fix this and connect my gateway to TTN server ?

**Comment by beitler** [comment] 2022-02-16 18:40
HTTP status code 403 points to an authentication problem.
Did you register your gateway on TTN using the proper gateway EUI (as printed in your logs):
<img width="249" alt="image" src="https://user-images.githubusercontent.com/2046752/154333607-f82f4627-6fb1-480b-b1e4-887344b18446.png">

Please consult with TTN as for the reasons of the authentication issue.

**Comment by oziesin** [comment] 2022-02-16 18:55
Yes, actually  it works with packet forwarder and chirpstack gateway bridge currently, but i wanna transition to basic station.

**Comment by beitler** [comment] 2022-02-17 10:55
Closing issue, since this is most probably not a bug. 
If you have general questions about basic station please use the [developer forum](https://forum.lora-developers.semtech.com/).

**Closed as completed by beitler** 2022-02-17 10:55 UTC
