### ISSUE TITLE
How to implement basic station after building

### ISSUE THREAD

**Issue by oziesin** [lorabasics/basicstation#151] opened 2022-02-11 08:40 UTC
Hi, i have been trying to build my own LoRaWAN Gateway, currently i am using Chirpstack server and UDP packet forwarder.

I built Lora-BasicStation using cross-compile for mips architecture(onion omega2s+) on my ubuntu machine. But i do not know how to continue.

I followed [this steps ](https://doc.sm.tc/station/quick.html) and i faced error below

![term](https://user-images.githubusercontent.com/54961819/153560663-ada59fd2-2a8b-4998-8a59-07c0e58caac8.png)

I guess existing file after the building is not proper for x86 ubuntu machine. How could i run basic station on my onion board ?

**Comment by beitler** [comment] 2022-02-11 11:01
Duplicate of https://forum.lora-developers.semtech.com/t/how-to-use-lora-basicstation-instead-of-udp-packet-forwarder/862. Closing.

**Closed as completed by beitler** 2022-02-11 11:01 UTC
